FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm i
# Ensure esbuild is installed correctly for the container's architecture
RUN npm rebuild esbuild
COPY . .
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN npm run build -- --debug

FROM nginx:1.19.6-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

WORKDIR /app
RUN chown -R nginx:nginx /app && chmod -R 755 /app && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

USER nginx

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
